using UnityEngine;

public class LevelManager : MonoBehaviour
{
    public GameObject obstaclePrefab;      // Prefab del obst치culo
    public Transform spawnPoint;           // Punto donde aparecer치n
    public float spawnInterval = 2f;       // Tiempo entre obst치culos
    private float timer = 0f;

    public DifficultyManager difficultyManager;

    void Update()
    {
        timer += Time.deltaTime;

        if (timer >= spawnInterval / difficultyManager.GetDifficulty())
        {
            GenerateObstacle();
            timer = 0f;
        }
    }

    void GenerateObstacle()
    {
        // Instancia un obst치culo en el punto indicado
        Instantiate(obstaclePrefab, spawnPoint.position, Quaternion.identity);
    }
}
